# Generated by Django 4.2.7 on 2023-11-15 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_customer_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='is_read_pd',
            field=models.BooleanField(default=False),
        ),
    ]
