# Generated by Django 4.2.7 on 2023-11-15 09:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_customer_is_read_pd'),
    ]

    operations = [
        migrations.CreateModel(
            name='Box',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Бокс')),
                ('price', models.DecimalField(decimal_places=1, max_digits=8, verbose_name='Стоимость')),
                ('length', models.IntegerField(verbose_name='Длина')),
                ('weigth', models.IntegerField(verbose_name='Ширина')),
                ('heigth', models.IntegerField(verbose_name='Высота')),
            ],
            options={
                'verbose_name': 'Бокс',
                'verbose_name_plural': 'Боксы',
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Статус',
                'verbose_name_plural': 'Статусы',
            },
        ),
        migrations.CreateModel(
            name='Storage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Склад')),
                ('description', models.TextField(verbose_name='Описание')),
                ('address', models.CharField(max_length=200, verbose_name='Адрес склада')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='RU', verbose_name='Телефон')),
                ('email', models.EmailField(max_length=256, unique=True, verbose_name='Email склада')),
                ('map', models.CharField(max_length=200, verbose_name='Карта')),
                ('temperature', models.DecimalField(decimal_places=1, max_digits=2, verbose_name='Температура на складе')),
                ('heigth', models.DecimalField(decimal_places=1, max_digits=3, verbose_name='Высота потолка')),
            ],
            options={
                'verbose_name': 'Склад',
                'verbose_name_plural': 'Склады',
            },
        ),
        migrations.CreateModel(
            name='UtmMark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=200, verbose_name='Ссылка')),
                ('count', models.IntegerField(verbose_name='Количество переходов')),
            ],
            options={
                'verbose_name': 'Переход',
                'verbose_name_plural': 'Переходы',
            },
        ),
        migrations.CreateModel(
            name='Rent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Дата начала аренды')),
                ('end_date', models.DateField(verbose_name='Дата окончания аренды')),
                ('box', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='box_rent', to='main.box', verbose_name='Бокс')),
                ('renter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_rent', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rent', to='main.status', verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Бокс',
                'verbose_name_plural': 'Боксы',
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('storage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image', to='main.storage', verbose_name='Склад')),
            ],
            options={
                'verbose_name': 'Картинка',
                'verbose_name_plural': 'Картинки',
            },
        ),
        migrations.AddField(
            model_name='box',
            name='storage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='box', to='main.storage', verbose_name='Склад'),
        ),
    ]
