# Generated by Django 4.2.7 on 2023-11-15 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_image_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rent',
            options={'verbose_name': 'Бокс в аренде', 'verbose_name_plural': 'Боксы в аренде'},
        ),
    ]
