# Generated by Django 4.2.7 on 2023-11-15 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_rent_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='box',
            name='floor',
            field=models.IntegerField(default=1, verbose_name='Этаж'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='storage',
            name='city',
            field=models.CharField(default=1, max_length=50, verbose_name='Город'),
            preserve_default=False,
        ),
    ]
