# Generated by Django 4.2.7 on 2023-11-15 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_box_floor_storage_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storage',
            name='heigth',
            field=models.DecimalField(decimal_places=2, max_digits=3, verbose_name='Высота потолка'),
        ),
        migrations.AlterField(
            model_name='storage',
            name='temperature',
            field=models.DecimalField(decimal_places=2, max_digits=3, verbose_name='Температура на складе'),
        ),
    ]
