# Generated by Django 4.2.7 on 2023-11-15 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_storage_heigth_alter_storage_temperature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storage',
            name='heigth',
            field=models.DecimalField(decimal_places=1, max_digits=3, verbose_name='Высота потолка'),
        ),
        migrations.AlterField(
            model_name='storage',
            name='temperature',
            field=models.DecimalField(decimal_places=1, max_digits=3, verbose_name='Температура на складе'),
        ),
    ]
