# Generated by Django 4.2.7 on 2023-11-18 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_city_order_storage_city_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery',
            field=models.BooleanField(blank=True, null=True, verbose_name='Доставка'),
        ),
        migrations.AlterField(
            model_name='order',
            name='loaders',
            field=models.BooleanField(blank=True, null=True, verbose_name='Грузчики'),
        ),
        migrations.AlterField(
            model_name='order',
            name='text',
            field=models.TextField(blank=True, null=True, verbose_name='Примечание'),
        ),
    ]
