# Generated by Django 4.2.7 on 2023-11-18 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_order_delivery_alter_order_loaders_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_status', to='main.status', verbose_name='Статус'),
        ),
        migrations.CreateModel(
            name='RemindDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField(verbose_name='количество дней')),
                ('status', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='remind_day', to='main.status', verbose_name='статус')),
            ],
            options={
                'verbose_name': 'Напоминание',
                'verbose_name_plural': 'Напоминания',
            },
        ),
    ]
