# Generated by Django 4.2.7 on 2023-11-19 07:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_callbackorderstatus_remindday_callbackorder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='utmmark',
            name='count',
        ),
        migrations.RemoveField(
            model_name='utmmark',
            name='url',
        ),
        migrations.AddField(
            model_name='utmmark',
            name='check_in_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Время захода'),
        ),
        migrations.AddField(
            model_name='utmmark',
            name='utm_campaign',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Название компании'),
        ),
        migrations.AddField(
            model_name='utmmark',
            name='utm_content',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Идентификатор объявления'),
        ),
        migrations.AddField(
            model_name='utmmark',
            name='utm_medium',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Тип траффика'),
        ),
        migrations.AddField(
            model_name='utmmark',
            name='utm_source',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Источник UTM'),
        ),
        migrations.AddField(
            model_name='utmmark',
            name='utm_term',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Ключевое слово'),
        ),
    ]
