# Generated by Django 4.2.7 on 2023-11-19 11:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_remove_utmmark_count_remove_utmmark_url_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='utmmark',
            options={'verbose_name': 'UTM метка', 'verbose_name_plural': 'UTM метки'},
        ),
        migrations.RemoveField(
            model_name='utmmark',
            name='check_in_date',
        ),
        migrations.AddField(
            model_name='utmmark',
            name='link_counter',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Количество переходов'),
        ),
    ]
