# Generated by Django 4.2.7 on 2023-11-20 07:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_alter_utmmark_options_remove_utmmark_check_in_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storage',
            name='map',
            field=models.CharField(max_length=1000, verbose_name='Карта'),
        ),
    ]
