# Generated by Django 4.2.7 on 2023-11-21 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_alter_storage_map_remindday'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='measurement',
            field=models.BooleanField(blank=True, null=True, verbose_name='Замерщик'),
        ),
        migrations.AddField(
            model_name='order',
            name='rise_price',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=8, null=True, verbose_name='Цена'),
        ),
    ]
